[package]
name = "appstream-rs"
version = "0.1.0"
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
gzip = ["flate2"]


[dependencies]
url = { version = "2.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_derive = "1.0"
quick-xml = { version = "0.17", features = [ "serialize" ] }
anyhow = "1.0"
serde_json = "1.0"
strum = "0.18"
strum_macros = "0.18"

[dependencies.flate2]
version = "1.0"
optional = true